spring:
  application:
    name: consumer
server:
  port: 8200

eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的ip地址
  client:
    fetch-registry: true #从eureka上来获取服务的注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka/
